name: Compile and Test 

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: LIGO Compile
              run: male ligo-compile
            - name: LIGO Test
              run: make ligo-test